########################
### RP API documents
########################
rpapidoc:
  describe:
    authorization:
      redirect-authorization: |
        認証・ユーザ情報提供ページへのリダイレクトを行います。
      fetch-token: |
        アクセストークンおよびIDトークンを取得します。
