########################
### RP API documents
########################
rpapidoc:
  describe:
    authorization:
      redirect-authorization: |
        認証・ユーザ情報提供ページへのリダイレクトを行います。
      demand-token: |
        アクセストークンおよびIDトークンを要求します。
      fetch-userinfo: |
        ユーザ情報を取得します。
