########################
### OP API documents
########################
opapidoc:
  describe:
    authorization:
      authorize: |
        認証・ユーザ情報提供画面へリダイレクトします。
      certificate: |
        ユーザID, パスワードによる認証を行い、認可コードを発行します。
      issue-token: |
        アクセストークンおよびIDトークンを発行します。
      fetch-userinfo: |
        UserInfoを取得します。
