########################
### OP API documents
########################
opapidoc:
  describe:
    authorization:
      authorize: |
        認可トークンを発行し、ログイン画面へリダイレクトします。
      certificate: |
        ユーザID, パスワードによる認証を行います。
      fetch-userinfo: |
        UserInfoを取得します。
