services:
  db:
    container_name: opdb
    image: mariadb:latest
    ports:
      - 3307:3306
    volumes:
      - ./volume/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
